### ISSUE TITLE
error: failed to run custom build command for `openssl-sys v0.9.83`

### ISSUE THREAD

**Issue by davehorner** [de-vri-es/webhook-httpd#11]
```
webhook-httpd>cargo run
    Updating crates.io index
  Downloaded textwrap v0.11.0
  Downloaded tokio-openssl v0.6.3
  Downloaded tokio-stream v0.1.10
  Downloaded unsafe-libyaml v0.2.4
  Downloaded structopt v0.3.26
  Downloaded serde_yaml v0.9.13
  Downloaded openssl-sys v0.9.83
  Downloaded proc-macro2 v1.0.46
  Downloaded hmac v0.12.1
  Downloaded time v0.1.44
  Downloaded h2 v0.3.17
  Downloaded syn v1.0.102
  Downloaded openssl v0.10.48
  Downloaded chrono v0.4.22
  Downloaded libc v0.2.135
  Downloaded subtle v2.4.1
  Downloaded structopt-derive v0.4.18
  Downloaded iana-time-zone v0.1.51
  Downloaded heck v0.3.3
  Downloaded clap v2.34.0
  Downloaded strsim v0.8.0
  Downloaded openssl-macros v0.1.0
  Downloaded 22 crates (2.1 MB) in 6.44s
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.46
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.5
   Compiling syn v1.0.102
   Compiling winapi v0.3.9
   Compiling version_check v0.9.4
   Compiling serde_derive v1.0.145
   Compiling cfg-if v1.0.0
   Compiling serde v1.0.145
   Compiling log v0.4.17
   Compiling memchr v2.5.0
   Compiling windows_x86_64_msvc v0.36.1
   Compiling futures-core v0.3.24
   Compiling windows_x86_64_msvc v0.42.0
   Compiling pin-project-lite v0.2.9
   Compiling typenum v1.15.0
   Compiling bytes v1.2.1
   Compiling windows-sys v0.36.1
   Compiling generic-array v0.14.6
   Compiling tokio v1.24.2
   Compiling cc v1.0.73
   Compiling once_cell v1.15.0
   Compiling pkg-config v0.3.25
   Compiling vcpkg v0.2.15
   Compiling libc v0.2.135
   Compiling tokio-macros v1.8.0
   Compiling windows-sys v0.42.0
   Compiling openssl-sys v0.9.83
   Compiling socket2 v0.4.7
   Compiling futures-task v0.3.24
error: failed to run custom build command for `openssl-sys v0.9.83`

Caused by:
  process didn't exit successfully: `c:\working\rust\webhook-httpd\target\debug\build\openssl-sys-ff8f954b7575bd8d\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  note: vcpkg did not find openssl: Could not find Vcpkg tree: No vcpkg installation found. Set the VCPKG_ROOT environment variable or run 'vcpkg integrate install'

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-pc-windows-msvc
  $TARGET = x86_64-pc-windows-msvc
  openssl-sys = 0.9.83


  It looks like you're compiling for MSVC but we couldn't detect an OpenSSL
  installation. If there isn't one installed then you can try the rust-openssl
  README for more information about how to download precompiled binaries of
  OpenSSL:

  https://github.com/sfackler/rust-openssl#windows
```

Is there a suggested package or step I should take next?

**Comment by davehorner** [comment]
```
choco install openssl
set OPENSSL_DIR=C:\Program Files\OpenSSL-Win64
```

leaves me to the unix related issues.
```
   Compiling webhook-httpd v0.1.4 (C:\working\rust\webhook-httpd)
error[E0433]: failed to resolve: could not find `unix` in `os`
   --> src\main.rs:376:15
    |
376 |     use std::os::unix::ffi::OsStrExt;
    |                  ^^^^ could not find `unix` in `os`

error[E0432]: unresolved import `tokio::signal::unix`
 --> src\main.rs:9:20
  |
9 | use tokio::signal::unix::{signal, SignalKind};
  |                    ^^^^ could not find `unix` in `signal`

error[E0599]: no function or associated item named `from_bytes` found for struct `OsStr` in the current scope
   --> src\main.rs:381:39
    |
381 |             command.env("CONTENT_TYPE", OsStr::from_bytes(content_type.as_bytes()));
    |                                                ^^^^^^^^^^ function or associated item not found in `OsStr`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   + use structopt::clap::osstringext::OsStrExt3;
    |

Some errors have detailed explanations: E0432, E0433, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `webhook-httpd` (bin "webhook-httpd") due to 3 previous errors
```

**Comment by davehorner** [comment]
```
(base) c:\working\rust\webhook-httpd>cargo run --config example-config.yaml
error: failed to load config from `c:\working\rust\webhook-httpd\example-config.yaml`

Caused by:
  could not parse TOML configuration in `c:\working\rust\webhook-httpd\example-config.yaml`

Caused by:
  TOML parse error at line 3, column 13
    |
  3 | bind-address: "::"
    |             ^
  expected `.`, `=`
```
the example config isn't valid for me.

**Comment by de-vri-es** [comment]
Hey! Sorry for the late reply.

Regarding the openssl build failure: the easiest fix is to enable the `static-openssl` feature:
```
cargo build|run|install  --features static-openssl
```

Regarding the unix only features: I've added alternative for non Unix platforms and released it as 0.1.5. So if you update it should compile on windows!

Regarding the last error, I'm not sure why you're seeing that. Did you modify the code to use TOML? Because `webhook-httpd` reads the configuration as a YAML file, not TOML.

**Comment by de-vri-es** [comment]
And of course, thank you for reporting the issues! Can't fix them if I don't know about them :)

**Comment by davehorner** [comment]
> Regarding the openssl build failure: the easiest fix is to enable the static-openssl feature:
I did see the note and tried that.  I did try it and that did not work for me.

A little persistence and I found an alternative way past that; it might be worth noting the solution in the readme.  I will let you know on 0.1.5.

No modifications, it came out the box speaking TOML parse errors.

**Comment by davehorner** [comment]
features static-openssl works fine when a working perl is present on the system.  I had a strawberry perl from 2014 that would not uninstall.  I cleared that and both methods are working.

I was not hit with a TOML error this time.  /print-env is not working as env is not a good command for windows.
I gave this a go.
```
   - url: "/print-cmd"
     commands:
       - cmd: ["cmd.exe","/c","set"]
```

```
curl -X POST http://localhost:8091/print-cmd
thank you, come again
```
I see the output of the set in the console window.  Windows is always fun having to tunnel thru cmd.exe.
I'd like to have a webhook that just writes files to a folder.

The good news is that the code is building and running in windows.

**Comment by davehorner** [comment]
I think this ticket can be closed but there's no discussion tab so I'll take advantage.

```
  - url: "/print-cwd"
    commands:
      - cmd: ["cmd.exe","/c","cd"]

  - url: "/multipart"
    commands:
      - cmd: ["cmd.exe","/c","target\\debug\\examples\\multipart.exe"]
        stdin: request-body
```

I want to be able to do something like:
```
curl -X POST -F "key1=value1" -F "key2=value2" -F "file=@Cargo.toml"   http://localhost:8091/multipart
thank you, come again
```

I'm not seeing the variables yet it is getting the content-type from the env and data from stdin
I worked on a few different implementations - tried using the multipart crate.  still think that might be the way to go.
this is what I've got tonight.  its not working yet.
https://github.com/de-vri-es/webhook-httpd/commit/82af2d02c3caf5162ba2ede8d6f7d3e341a198bc

let me know if there's an easier way easier way to do this sort of thing.

**Comment by davehorner** [comment]
https://github.com/de-vri-es/webhook-httpd/commit/7bddfcb2ad44fda3e84618c3004b287cba33e6e2

I have a working file upload example.  if you'd like to include it in the repo as an example I can provide a PR.
thanks for the code and your responses.

**Comment by de-vri-es** [comment]
> ```
> (base) c:\working\rust\webhook-httpd>cargo run --config example-config.yaml
> error: failed to load config from `c:\working\rust\webhook-httpd\example-config.yaml`
> 
> Caused by:
>   could not parse TOML configuration in `c:\working\rust\webhook-httpd\example-config.yaml`
> 
> Caused by:
>   TOML parse error at line 3, column 13
>     |
>   3 | bind-address: "::"
>     |             ^
>   expected `.`, `=`
> ```
> 
> the example config isn't valid for me.

Ah, I see, the problem here was running `cargo run --config ...` instead of `cargo run -- --config ...`. The config file was passed to cargo instead of `webhook-httpd`.

**Comment by de-vri-es** [comment]
> I have a working file upload example. if you'd like to include it in the repo as an example I can provide a PR.
> thanks for the code and your responses.

Yeah, it sounds interesting. Would be nice as an example in the repository!

**Comment by davehorner** [comment]
It would be nice to be able to set environment variables per hook.  That's something I might be able to do if you're down.  

Looks relatively straight forward.  Add a pub envvars: Vec<String> to Hook, and could be added to run_command right next to set_request_environment.

Do you have thoughts on that?
